name             'app'
maintainer       'The Authors'
maintainer_email 'you@example.com'
license          'all_rights'
description      'Installs/Configures app'
long_description 'Installs/Configures app'
version          '0.1.0'
depends 'mysql', '~> 6.0'
